services:
  - type: web
    name: backend_dev
    env: node
    buildCommand: yarn; yarn build
    startCommand: yarn start
    region: singapore
    plan: free
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: db_dev
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: db_dev
          property: port
      - key: DATABASE_USERNAME
        fromDatabase:
          name: db_dev
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: db_dev
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: db_dev
          property: database
      - key: NODE_VERSION
        value: 18.17.1
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: false
      - key: JWT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_ACCESS_SECRET
        sync: false
      - key: AWS_REGION
        value: ap-southeast-3
      - key: AWS_BUCKET
        value: backend-cms-bucket

databases:
  - name: db_dev
    databaseName: db_dev 
    user: db_dev
    region: singapore
    plan: free
    postgresMajorVersion: 15
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    